In [46]:
import numpy as np

In [47]:
list1 = ([1 , 2 , 3], [4 ,5 ,6] , [7 , 8 , 9])
arr = np.array(list1)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr = np.zeros(5 , dtype='int')
arr

array([0, 0, 0, 0, 0])

In [50]:
arr = np.zeros((5 , 5) , dtype='int')   #(rows , column)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [51]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [52]:
array = np.eye(4 , dtype="int")   #diagnol matrix
array

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [53]:
arr = np.linspace(1 , 5 , 10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [54]:
array = np.random.rand(5)    # 0 to 1 range bydefault
array

array([0.34670019, 0.99116694, 0.36088705, 0.04277815, 0.60679717])

In [55]:
array = np.random.rand(5 , 5)   
array = np.array(array , dtype='int')
array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [56]:
arr = np.random.randint(1 , 100 , 10)
arr
# arr = np.linspace(1 , 100 , 10)
# arr

array([ 2, 36, 98, 21, 85, 88, 62, 13, 67, 18], dtype=int32)

In [59]:
arr = np.random.randn(5)
arr

array([ 0.32460294, -2.27794268,  2.49836964, -1.16022659,  0.60499718])

In [62]:
# dtype= 'object'
arr = np.array([(1 , 'hassan' , 19) , (2 , 'Ali' , 18)] , dtype=[('id' , 'int') , ('name' , 
'U10') , ('age','int')])
print(arr)

[(1, 'hassan', 19) (2, 'Ali', 18)]


In [66]:
# arr['id']
# arr['age']
# arr['name']


array(['hassan', 'Ali'], dtype='<U10')